### PR TITLE
Better handling for cache key errors

### LINKED ISSUE #23: Useless error when cache key does not match
If the autolab cli's encryption key for the .arcache file does not match what was used to write it, all that's displayed is openssl's error (which is even less than useful because openssl's error strings are not loaded). The tool should either diagnose the mismatch and describe it, or proactively discard the cache

error:06065064:lib(6):func(101):reason(100):evp_enc.c:592:

### PR DESCRIPTION
**Pull request by damianhxy**
When loading tokens from the `.arcache` fails, proactively delete the file, so that the user is forced to set-up the CLI again.

Also, remove `grading_deadline` logic.

Closes #23

To test:
- Set up autolab CLI (in debug mode)
- Try loading an assessment, make sure there no `string_to_time parse fail!` messages (previously caused by attempting to parse `grading_deadline`)
- Ensure that `.autolab/.arcache` file exists in user home directory
- Update `crypto_key` in `app_credentials.h`, and rebuild CLI
- Try loading an assessment again, get error message

Screenshot 2024-05-15 at 22 17 45

- Check that `.autolab/.arcache` file has been removed
- Try loading an assessment again - no more error about `load_tokens`

Screenshot 2024-05-15 at 22 18 04

### CODE REVIEW

File: src/context_manager/context_manager.cpp [hunk 1]
```diff
@@ -88,7 +95,14 @@ bool load_tokens(std::string &at, std::string &rt) {
             raw_result, TOKEN_CACHE_FILE_MAXSIZE);
   LogDebug("read size " << num_read << "\n");
 
-  if (!token_pair_from_string(raw_result, num_read, at, rt)) return false;
+  try {
+    if (!token_pair_from_string(raw_result, num_read, at, rt)) return false;
+  } catch (Autolab::CryptoException &e) {
+    Logger::fatal << "OpenSSL error in load_tokens." << Logger::endl;
```
Comment (20wildmanj) [inline src/context_manager/context_manager.cpp]: This is no longer a fatal error so not the most accurate, though I do see that there is only info / debug options for logging otherwise right now

**Review by 20wildmanj — APPROVED** [review]
verified that ignoring cache on crypto error works by recreating the error found with autolab V3 on AFS, setup now works without having to manually delete the cache. LGTM besides logging comment.

File: src/context_manager/context_manager.cpp (hunk 1 above)
Comment (damianhxy) [reply src/context_manager/context_manager.cpp]: Switched to `LogDebug`

**Debug mode**
Screenshot 2024-05-21 at 13 32 31

**Release mode**
Screenshot 2024-05-21 at 13 33 48
